### ISSUE TITLE
Bad build

### ISSUE THREAD

**Issue by prifio** [SecondDerivative/Arena#1]
Сейчас у нас не проходит тест на build сервере. Обращение к защищенной памяти.

**Comment by opestov** [comment]
В строке 256 в логе АппВейора есть предупреждение, что, архитектура тестового проекта не совпадает с архитектурой основного:

```
C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3270: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\projects\arena\SFMLApp\bin\Debug\SFMLApp.exe", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [C:\projects\arena\Tests\Tests.csproj]
```

Можно попробовать изменить ее на икс86.

**Comment by prifio** [comment]
Я сделал отдельную ветку для возни со всем этим. В ней, в csproj'е обоих проектов, везде, где логично (а последних коммитах, и где не очень), заменил AnyCPU и x64 на x86. Warning остался. Test failed.(и ещё я ветку с опечаткой назвал)

**Comment by prifio** [comment]
После долгого изменения XML файлов, warning ушёл. Но я это делал без среды, по этому могут быть проблемы с тем, что это вообще может работать. Вроде build succeeded, но всё равно падают тесты

**Comment by prifio** [comment]
Сейчас есть новый PR. Не использует runner.VS. Вместо этого запускайте батник

**Comment by prifio** [comment]
Сейчас более-менее все работает
